@startuml
'https://plantuml.com/class-diagram

class Ship {
# shipName: String
# yearBuilt: String

+ getShipName(): String
+ setShipName(in shipName: String): void
+ getYearBuilt(): String
+ setYearBuilt(in yearBuilt: String): void
+ toString(): String
+ printShip(): void
}



@enduml