@startuml
'https://plantuml.com/object-diagram

object "<u>c1Instructor:Instructor</u>" as instructor{
firstName = "Nima"
lastName = "Davarpanah"
officeNumber = "3-2636"
}

object "<u>c1Textbook:Textbook</u>" as textbook{
author = "Robert Cecil Martin"
publisher = "Pearson"
title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}

object "<u>c1:Course</u>" as course{
name = "CS5800 - Advanced Software Engineering"

}


textbook --o course
instructor --o course


@enduml
