@startuml
'https://plantuml.com/object-diagram

object "<u>phpDemo1:Folder</u>" as root {
name = "php_demo1"
}
object "<u>subFolder:Folder</u>" as sourceFiles {
name = "Source Files"
}

root *-- sourceFiles

object "<u>subFolder:Folder</u>" as includePath{
name = "Include Path"
}

root *-- includePath

object "<u>subFolder:Folder</u>" as remoteFiles {
name = "Remote Files"
}

root *-- remoteFiles



object "<u>subFolder:Folder</u>" as phalcon {
name = ".phalcon"
}
object "<u>subFolder:Folder</u>" as cache {
name = "cache"
}
object "<u>subFolder:Folder</u>" as public {
name = "public"
}

sourceFiles *-- phalcon
sourceFiles *--cache
sourceFiles *-- public


object "<u>file:File</u>" as htaccess {
name = ".htaccess"
}
object "<u>file:File</u>" as htrouter {
name = ".htrouter.php"
}
object "<u>file:File</u>" as index {
name = "index.html"
}

public *-- htaccess
public *-- htrouter
public *-- index

note as n1
    For this diagram, I used **subfolder** as the
    instance name for subfolder instances and **file**
    as the name for File instances since that is
    how it is instantiated in the Folder class.

    Otherwise, the folder and file instance names
    for all other instances besides phpDemo1 would
    be blank.
end note
@enduml
